### ISSUE TITLE
Add "backend" system.

### ISSUE THREAD

**Issue by Caroga** [010PHP/010php.nl#25]
So yeah, we basically need to be able to post news items on our frontpage, edit pages, etc etc.
So a small CMS-like system would come in handy.
I'd like to discuss the possible implementations of such features, what we would like to use and why.

Key features that I think that are needed are:
- add/update/delete frontpage news items
  and sort them...
- Add/update/delete pages
  and sort them...
- Image upload to be placed inside the news items. 

Lets keep it KISS.

**Comment by reenl** [comment]
I'd say add a screenshot of what you want to be changable. Also a CMS means someone has to login, while via Github we can all change and PR it. I'd say Github is the best CMS for developers, if we completely automate deployments.

**Comment by Caroga** [comment]
That's true, but having to type out all the HTML is a bit annoying don't you think ? We could maybe go with Markdown or other stuff.

I should describe a bit more what people are expecting to see from our website. I've gathered this information some time ago with a survey I dropped via twitter.

* Talk recaps. Information about previous talks. Also about future meetups. This is what people would like to see, this is what we like to be able to present. This could be automated for some part, but monthly recaps are worth their time as this gives a good review about what happened and what people can expect from us.
* Media. I'd like to show media from Meetup.com. 
* Joind.In integration
* Provide a way to let community members interact with each other, other then being on Slack.
* More cowbell
* This is just a small list of everything I have gathered. This will do fine to begin with.  

Having all this in mind, I've got requests from people in the past where they are asking for subscribing to the meetups without having to signup for an account on meetup.com. Maybe having a mailinglist option for this is something worth thinking of. This does imply having a account on 010PHP. Maybe being able to login using social media.

**Comment by marcojanssen** [comment]
Why not start with some simple page content (recaps) instead of all the bells and whistles. Perhaps we could generate it with https://sculpin.io which is a static page generator converting md/twig to static html

**Comment by Caroga** [comment]
So this is a pretty old ticket but we still require a CMS(like) system.  Now Sculpin is fine by me, but feels like it cannot take care of all the mentioned requirements above. 

Maybe we should trim the requirements a bit or look at something else, like Zulu?

**Comment by Caroga** [comment]
Also, a concept for the new site:
![010phpdesign2016](https://cloud.githubusercontent.com/assets/4005934/22055579/19be6ae6-dd5c-11e6-9b9d-12292d596717.jpg)
