### ISSUE TITLE
Meetup.com profile images are invalidating our SSL certificate

### ISSUE THREAD

**Issue by Caroga** [010PHP/010php.nl#30]
The meetup.com profile images are loaded over http instead of https, and meetup.com does not provide a https connection.
I was thinking of either having to create a reverse proxy so we can route the images through our own domain and make them available over our ssl connection or either remove them.
Any other suggestions ?

**Comment by reenl** [comment]
ch.ris suggested on slack:

> @caroga: quicker solution is this: https://photos4.meetupstatic.com/photos/member/7/8/c/thumb_216361932.jpeg >> https://www.meetupstatic.com/photos/member/7/8/c/thumb_216361932.jpeg (13KB)
> :)
> *.meetupstatic.com to www.meetupstatic and BAM, valid SSL :smile:

**Comment by Caroga** [comment]
+1, we should implement that.

**Comment by Caroga** [comment]
Fixed
