### ISSUE TITLE
Meetups and Github links don't work

### ISSUE THREAD

**Issue by WyriHaximus** [010PHP/010php.nl#34]
After a quick peek https://github.com/010PHP/010php.nl/blob/master/app/Resources/js/app.js#L16 seems to be the perpetrator but I don't know enough about the reasoning to put it there.

**Comment by Caroga** [comment]
Good catch!  
It was used for the single page navigation, but this is not being used anymore. I believe this could actually be removed.

**Comment by Caroga** [comment]
Solved in #36.
Thank you for reporting this!

**Comment by WyriHaximus** [comment]
No problem, keep up the good work :+1:
